basePath: /v2
definitions:
  model.Notification:
    type: object
  model.NotificationType:
    enum:
    - chat
    - post
    - friend-request
    type: string
    x-enum-varnames:
    - Chat
    - Post
    - FriendRequest
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is Dandelion Notification server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Dandelion Notification API
  version: "1.0"
paths:
  /notification:
    get:
      consumes:
      - application/json
      description: get all notifications
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get notifications
      tags:
      - notifications
    post:
      consumes:
      - application/json
      description: add a new notification
      parameters:
      - description: Add new notification
        in: body
        name: notification
        required: true
        schema:
          $ref: '#/definitions/model.Notification'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Add notification
      tags:
      - notifications
swagger: "2.0"
